# Generated by Django 5.1 on 2024-08-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='move_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
